# Generated by Django 2.0.7 on 2018-10-18 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('is_empty', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='1', max_length=10)),
                ('last_updated', models.DateTimeField()),
                ('store', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.Store')),
            ],
        ),
    ]
